server:
  port: 8761

spring:
  application:
    name: salesflow-discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

saledflow:
  deployment:
    environment: ${SALESFLOW_DEPLOYMENT_ENV:stage}
